### PR TITLE
Swift2 visual API

### PR DESCRIPTION
**Pull request by fotiDim**
Exposed some objects in order to be able to customise like the image:

PS: Updated the ObjC example to use the latest API

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! Particularly for updating the ObjC example, that's very helpful.

Can you explain how you used the newly public `contentView` to customize your implementation?

**Comment by fotiDim** [comment]
@nickoneill This is what I 've been doing to the content view:

``` objectivec
_multiPscope.contentView.backgroundColor = [UIColor darkBlueColor];
_multiPscope.contentView.layer.borderColor = [UIColor darkBlueColor].CGColor;
```

I just noticed the the ObjC example does not work as expected. If I use `[NotificationsPermission new]` it crashes looking for an init() method. If I use `[NotificationsPermission alloc]` it somehow understands it as ContactsPermission. This happens to every permission type. Any ideas what might be wrong?

**Comment by fotiDim** [comment]
Never mind. I just fixed it. The good old alloc/init did the trick. The problem was with NotificationsPermission which didn't carry an `init()` method but instead carried `initWithNotificationCategories()`.

I took the liberty to migrate every "new" call to alloc/init for consistency.

**Comment by bre7** [comment]
Nice.

 ~~Pending: Update README about new properties.~~ Done

Fix https://github.com/nickoneill/PermissionScope/pull/82/files#diff-6a54c2af707042d2afac7fd53538bb2dR38 if you can, it's the same comment as line 40

**Pull request merged**
