### PR TITLE
README.md moved from "Compile Sources" to "Copy Bundle Resources"

### PR DESCRIPTION
**Pull request by ky1ejs**
Noticed when using Carthage and receiving log errors stating that xcodebuild didn't know how to compile .md (expected, of course).

:)

### CODE REVIEW

**Comment by ky1ejs** [comment]
Also just fixed the Code Signing Identity for distribution as it was set to use development identities.

In our case, this was breaking our CI as Carthage was looking for a development ID and couldn't find one because we only keep a distribution signing cert and key pair on it, which I imagine is very common on other CI serves. Building the release config should sign with distribution IDs.

**Comment by nickoneill** [comment]
Thanks for this! I imagine this is something we'd have to deal with for our planned UI testing in Xcode 7 down the line.

Can you share what app you're using pscope for?

**Comment by ky1ejs** [comment]
No problem, pleasure! And thank you for the work on pscope! 

Sorry for my poor writing on the comments above (which I've now corrected. The heat here in London must have got to me!)

We're trying it out in our app, [Loot](http://lootapp.io). :smile:

**Comment by ky1ejs** [comment]
When do you think you'll make a new release? Perhaps a 0.6.1 so Carthage can see the improvements and corrects?

**Comment by nickoneill** [comment]
I'll push a new one out today with recent updates, there's a couple new things since the last release.

**Comment by ky1ejs** [comment]
Cool, good stuff, thanks. Got a bit excited with the version number I wrote there (before editing). Ha!

**Comment by nickoneill** [comment]
0.7 is tagged, let me know if that works for you.

**Comment by ky1ejs** [comment]
Awesome, thanks! Will take a look tomorrow morning.

**Comment by ky1ejs** [comment]
It's worked! Thanks!

**Pull request merged**
