### PR TITLE
Migrated to Swift 3 syntax.

### PR DESCRIPTION
**Pull request by jstheoriginal**
If anything looks off, just let me know and I'll updated it.

Note, I tested using the sample app and it works. The only exception in the sample app is the Enable Contacts button crashes the simulator on iOS 10 even before the pop-up asking for permission appears, but it works fine on an iOS 9.3 simulator. I added a //FIXME for this as well.

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! I'll check this out next week when I'm back at work.

**Comment by jstheoriginal** [comment]
Sounds good. 👍

**Comment by bre7** [comment]
Couple of changes (minor):
- Comment `first()` (located at https://github.com/nickoneill/PermissionScope/blob/master/PermissionScope/Extensions.swift#L38) since it's part of Swift 3 (http://swiftdoc.org/v3.0/protocol/Sequence/#func-first_).
- Replace `DispatchTime.now() + Double(Int64(0.1 * Double(NSEC_PER_SEC))) / Double(NSEC_PER_SEC)` with `DispatchTime.now() + .milliseconds(100)` or `DispatchTime.now() + 0.1`

**Comment by jstheoriginal** [comment]
@bre7 Did you mean to just comment the `first()` extension out, or remove it completely?

**Comment by bre7** [comment]
Comment the whole method for now.

**Comment by jstheoriginal** [comment]
Done like dinner.

**Comment by bre7** [comment]
👍

**Comment by blwinters** [comment]
I've updated my local version of PermissionScope to adopt the changes in these commits and almost everything is resolved. However, I'm getting an error with line 955 of PermissionScope.swift: `if let error = error where error.code == Int(CMErrorMotionActivityNotAuthorized.rawValue) {`. The error message says, "Value of type 'Error' has no member 'code'." Does anyone know what might be causing this? (I'm using Xcode 8 beta 4.)

**Comment by jstheoriginal** [comment]
@blwinters i saw that as well...it's a new issue that just arose in beta 4. I couldn't figure out how to correct it though, so hopefully it's just a property that's been hidden by mistake and will be fixed in beta 5.

**Comment by bre7** [comment]
@blwinters @jstheoriginal Related to `SE-0112` I think: http://ericasadun.com/2016/08/01/geomapping-the-swift-change-log/

**Comment by jstheoriginal** [comment]
good to know!

**Comment by bre7** [comment]
Can't seem to find the new `offsetInPlace`. `offsetBy` is the new non-mutating version and the only method with `offset` in it's declaration.

**Comment by ed-mejia** [comment]
Any chance to have an official swift3 branch any time soon? 🤔

**Comment by bre7** [comment]
Only thing needed is to fix offsetInPlace. I'll submit the other fixes later.

**Comment by ed-mejia** [comment]
I have a Swift-3 branch ready [here](https://github.com/ed-mejia/PermissionScope/tree/swift-3) if you want to have a look

> this branch is a fork from jstheoriginal but with support for Beta 4

**Comment by bre7** [comment]
Great. Only one minor detail: I think you can now use `.normal` instead of `UIControlState()` (e.g: button.setTitleColor)

Typo: `.now() + .milliseconds(100)` != `.now() + 1.0` (should be 0.1 but use .milliseconds for clarity)

**Comment by ed-mejia** [comment]
Good to know, I already update those too. 👍

**Comment by SaifAlDilaimi** [comment]
Any Plan to create a branch for this?

**Comment by SaifAlDilaimi** [comment]
Can someone explain to me how I can use this PR?

**Comment by ed-mejia** [comment]
@deada92 in your pod file:

`pod 'PermissionScope', :git => 'THE GIT URL', :branch => 'THE BRANCH NAME'`

**Comment by SaifAlDilaimi** [comment]
Hey @ed-mejia,

thx for the hint. I use xcode beta 6 and cocoapods 1.1.0.beta.1 and install it with:

`pod 'PermissionScope', :git => 'https://github.com/jstheoriginal/PermissionScope.git', :branch => 'swift-3'`

I still have 51 errors of these:

```
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:19:42: error: function types cannot have argument label 'status'; use '_' instead
public typealias statusRequestClosure = (status: PermissionStatus) -> Void
                                         ^
                                         _ 
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:20:42: error: function types cannot have argument label 'finished'; use '_' instead
public typealias authClosureType      = (finished: Bool, results: [PermissionResult]) -> Void
                                         ^
                                         _ 
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:20:58: error: function types cannot have argument label 'results'; use '_' instead
public typealias authClosureType      = (finished: Bool, results: [PermissionResult]) -> Void
                                                         ^
                                                         _ 
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:21:42: error: function types cannot have argument label 'results'; use '_' instead
public typealias cancelClosureType    = (results: [PermissionResult]) -> Void
                                         ^
                                         _ 
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:548:47: error: expected ',' joining parts of a multi-clause condition
        if let settingTypes = settings?.types where settingTypes != UIUserNotificationType() {
                                              ^~~~~
                                              ,
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:956:38: error: expected ',' joining parts of a multi-clause condition
                if let error = error where error.code == Int(CMErrorMotionActivityNotAuthorized.rawValue) {
                                     ^~~~~
                                     ,
```

Any idea why?

**Comment by bre7** [comment]
Swift 3 related... E.g: `where` is now `,`

**Comment by SaifAlDilaimi** [comment]
Ah, I was thinking the branch fixed the syntax.

Anyway I have fixed some other syntax related to the UIColor calls. 

I'm getting now this.. can you help me again?

```

/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:241:21: error: value of type 'CGRect' has no member 'offsetInPlace'
        headerLabel.frame.offsetInPlace(dx: -contentView.frame.origin.x, dy: -contentView.frame.origin.y)
        ~~~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:242:21: error: value of type 'CGRect' has no member 'offsetInPlace'
        headerLabel.frame.offsetInPlace(dx: 0, dy: -((dialogHeight/2)-50))
        ~~~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:246:19: error: value of type 'CGRect' has no member 'offsetInPlace'
        bodyLabel.frame.offsetInPlace(dx: -contentView.frame.origin.x, dy: -contentView.frame.origin.y)
        ~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:247:19: error: value of type 'CGRect' has no member 'offsetInPlace'
        bodyLabel.frame.offsetInPlace(dx: 0, dy: -((dialogHeight/2)-100))
        ~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:250:21: error: value of type 'CGRect' has no member 'offsetInPlace'
        closeButton.frame.offsetInPlace(dx: -contentView.frame.origin.x, dy: -contentView.frame.origin.y)
        ~~~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:251:21: error: value of type 'CGRect' has no member 'offsetInPlace'
        closeButton.frame.offsetInPlace(dx: 105, dy: -((dialogHeight/2)-20))
        ~~~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:252:21: error: value of type 'CGRect' has no member 'offsetInPlace'
        closeButton.frame.offsetInPlace(dx: self.closeOffset.width, dy: self.closeOffset.height)
        ~~~~~~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:262:20: error: value of type 'CGRect' has no member 'offsetInPlace'
            button.frame.offsetInPlace(dx: -contentView.frame.origin.x, dy: -contentView.frame.origin.y)
            ~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:263:20: error: value of type 'CGRect' has no member 'offsetInPlace'
            button.frame.offsetInPlace(dx: 0, dy: -((dialogHeight/2)-160) + CGFloat(index * baseOffset))
            ~~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:283:27: error: value of type 'CGRect' has no member 'offsetInPlace'
                    label.frame.offsetInPlace(dx: -self.contentView.frame.origin.x, dy: -self.contentView.frame.origin.y)
                    ~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:284:27: error: value of type 'CGRect' has no member 'offsetInPlace'
                    label.frame.offsetInPlace(dx: 0, dy: -((dialogHeight/2)-205) + CGFloat(index * baseOffset))
                    ~~~~~~^~~~~ ~~~~~~~~~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:610:23: error: value of type 'DispatchQueue' has no member 'after'
        DispatchQueue.main.after(
        ~~~~~~~~~~~~~~^~~~ ~~~~~
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:955:18: error: contextual member 'main' has no associated value
            to: .main()) { activities, error in
                 ^
/Volumes/SDIntern/Entwicklung/Apps/PrayForTheWorld/Pods/PermissionScope/PermissionScope/PermissionScope.swift:79:39: error: unable to infer closure type in the current context
    lazy var defaults: UserDefaults = {

```

**Comment by bre7** [comment]
Everything is Swift 3 related. Non-existent methods, etc. Try to fix them using the docs or wait for final PR

**Comment by SaifAlDilaimi** [comment]
okay thx

**Comment by bre7** [comment]
Swift 3 (Xcode 8.0 beta 6) branch committed. Closing PR

``` ruby
pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git', :branch => 'swift3'
```

**Comment by SaifAlDilaimi** [comment]
thank you 👍

**Pull request closed without merging**
