### PR TITLE
Denied status and Camera/Microphone/Photos added

### PR DESCRIPTION
**Pull request by bre7**
Added new button style (same as Authorized, inverse tint color) and title for DENIED permissions, alert is also shown asking the user to go to settings....) (#2 ?)

Camera/Microphone permissions added (#1).
~~Bug: Microphone isn't working 100%. Using the test project, it says "ALLOWED MICROPHONE" when it should say "ALLOW" since the permissions where never granted before.~~

### CODE REVIEW

**Comment by nickoneill** [comment]
This is great, thanks! I'll check it out this afternoon.

**Comment by bre7** [comment]
Photos added. (#3)

~~Bug: When Photos is requested, Microphone is taken into account. The button title says "Photos" but the triggered alert doesn't: "Permission for Microphone was denied." (No mixup like before, not sure why it's happening)
statusPhotos() says Authorized but PHPhotoLibrary.authorizationStatus() states .NotDetermined...was working on an old verion~~

**Comment by nickoneill** [comment]
Thank you! I made a couple fixes that prevented the denied alert from showing, everything else was excellent though.

**Comment by bre7** [comment]
Np, thanks for the fixes

**Pull request merged**
