### PR TITLE
Objective-C compatibility

### PR DESCRIPTION
**Pull request by felix-dumit**
I basically just redid the changes from #38 without the extra whitespace and other changes.

I also finished the sample objc example. I did not do extensive tests but everything looks good.

Probably still need to update the documentation.

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! This looks excellent, exactly what I was looking for from the other commit.
- What was the issue with the closure stuff? I haven't done any work in objc with swift so I'm curious, I don't think I've heard of this particular issue.
- Similarly to the other commit: I understand the need to convert the structs to classes, I'm slightly concerned about the value-to-reference change but I don't see any obvious implications unless you're holding onto the config objects after passing them to a pscope controller (which I can't think of a usecase for). Any thoughts on this @bre7?

**Comment by bre7** [comment]
I don't think there are any retention issues between Configs and PScope itself

**Comment by felix-dumit** [comment]
@nickoneill I'm not sure the issue with the closure, I ran without that part and it works as well. 
I can push a version without it, maybe @valentin7 can explain what the original issue was.

Regarding the mutability, something I did in the example was to reuse the same config for notifications for the singlePscope and the multiPscope. What we can do just to be safe is to copy the config before adding to the internal array. What do you think?

**Comment by nickoneill** [comment]
After thinking about it some more, copying the config classes is probably overkill. We'll deal with it if we have a problem later.

Let's move the closures to the usual syntax since we can't figure out why they were changed. Then this'll be ready to merge.

**Comment by nickoneill** [comment]
Didn't realize this was done. I'll merge this in later today. Thank you @felix-dumit!

**Comment by fotiDim** [comment]
@nickoneill Any news on the merge?

**Comment by nickoneill** [comment]
Sorry for the wait, I'll be testing and doing a new cocoapods/carthage release soon so this'll be easier to get at.

**Pull request merged**
