### PR TITLE
use Contacts framework for > iOS 9 apps

### PR DESCRIPTION
**Pull request by rynecheow**

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks for the pr @rynecheow!

Is there a benefit or difference from requesting this permission via the new iOS 9 method?

**Comment by rynecheow** [comment]
As AddressBook methods are deprecated on iOS 9 and Contacts framework is providing a more thread-safe way of accessing contacts - i think we should allow the framework to use the more preferred method for iOS 9 users.

Ref: https://developer.apple.com/library/prerelease/mac/documentation/Contacts/Reference/Contacts_Framework/index.html

**Comment by nickoneill** [comment]
Oh, I didn't even realize the old address book items were deprecated in iOS 9. Yeah, we should definitely  start moving people over to this when possible.

**Comment by nickoneill** [comment]
This looks good @rynecheow, remove the `.DS_Store` files from this commit and we'll get it merged in.

**Comment by rynecheow** [comment]
Updated.

**Comment by nickoneill** [comment]
Thanks! Definitely stick that line in your global gitignore too, nobody likes `.DS_Store` files :)

**Pull request merged**
