### PR TITLE
Improving German translations

### PR DESCRIPTION
**Pull request by VFUC**
Some phrases and choice of words didn't seem very native.

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! Any idea how this impacts the display of the strings in the PermissionScope dialog? This definitely seems like it increases the character count by a bunch :)

**Comment by winkelsdorf** [comment]
+1 for the approach
-1 for the character count and addressing users informally (_"Bitte aktiviere den Zugriff"_ is informal, formally is _"Bitte aktivieren Sie den Zugriff"_)

Probably there's need to address the latter with two sets, like GermanInformal.strings and German.strings ;) ^^ While I don't think NSFormatter et al have a setting for being "informal".

**Comment by nickoneill** [comment]
@winkelsdorf I'm going to defer to you on which german strings should be included. I would rather keep a single list of German strings that we encourage people to use, I'm guessing that's more on the informal side but I don't know the standard for apps.

**Comment by winkelsdorf** [comment]
Sorry for being late. 

I am totally fine with the current informal translation, so give it a go. Despite I don't have any numbers, I would say that more than 95% of the local Apps use informal language (2nd person singular).

👍 for the merge.

**Pull request merged**
